# Generated by Django 4.1.1 on 2023-01-29 11:19

from django.db import migrations, models
import mep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('about_me', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MepProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('feature', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=mep.models.upload_to)),
            ],
        ),
    ]
