# Generated by Django 4.1.1 on 2023-01-31 03:12

from django.db import migrations, models
import mep.models


class Migration(migrations.Migration):

    dependencies = [
        ('mep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mepprojects',
            name='image_url',
            field=models.URLField(default='http://goal.com'),
        ),
        migrations.AlterField(
            model_name='mepprojects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mep.models.upload_to, verbose_name='Image'),
        ),
    ]
