# Generated by Django 4.1.1 on 2023-01-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mep', '0002_mepprojects_image_url_alter_mepprojects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mepprojects',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
