# Generated by Django 4.1.1 on 2023-01-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mep', '0003_alter_mepprojects_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mepprojects',
            name='image_url',
        ),
    ]
